import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read = path => readFileSync(new URL('../'+path, import.meta.url), 'utf8');
const html = read('app/index.html');
const block = html.split('id="fidelity-context"')[1].split('<nav ')[0];
assert.equal((block.match(/class="fidelity-context-trigger"/g)||[]).length, 2);
assert.equal((block.match(/class="fidelity-context-current"/g)||[]).length, 2);
assert.equal((block.match(/será implementada em uma etapa futura/g)||[]).length, 2);
assert.doesNotMatch(block, /Produto|Studio Aurora|Projeto Lunar|Operações|Marketing/);
assert.match(block, /Quadro de trabalho/);
assert.match(read('app/js/fidelity-v2.js'), /kanban: \['Quadro', 'Quadro de trabalho'/);
const panels = {workspace: {hidden:true}, board: {hidden:true}};
const triggers = Object.keys(panels).map(id => ({id, events:{}, attrs:{'aria-controls':id,'aria-expanded':'false'}, getAttribute(k){return this.attrs[k]},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,fn){this.events[k]=fn},focus(){this.focused=true}}));
const root = {dataset:{}, events:{},querySelectorAll(){return triggers},addEventListener(k,fn){this.events[k]=fn},contains(node){return node===this||triggers.includes(node)}};
const docEvents = {};
const document = {getElementById:id=>id==='fidelity-context'?root:panels[id],addEventListener:(k,fn)=>docEvents[k]=fn};
const source = read('app/js/context-selector.js');
assert.doesNotMatch(source, /fetch\(|localStorage|sessionStorage|state\./);
vm.runInNewContext(source.replace('export function','function'), {document});
const [workspace,board] = triggers;
workspace.events.click();assert.equal(panels.workspace.hidden,false);assert.equal(workspace.attrs['aria-expanded'],'true');
board.events.click();assert.equal(panels.workspace.hidden,true);assert.equal(panels.board.hidden,false);
board.events.click();assert.equal(panels.board.hidden,true);
workspace.events.click();let prevented=false,stopped=false;root.events.keydown({key:'Escape',preventDefault(){prevented=true},stopPropagation(){stopped=true}});assert.ok(prevented&&stopped&&workspace.focused);assert.equal(panels.workspace.hidden,true);
workspace.events.click();docEvents.click({target:workspace});assert.equal(panels.workspace.hidden,false);docEvents.click({target:{}});assert.equal(panels.workspace.hidden,true);
board.events.click();root.events.focusout({relatedTarget:workspace});assert.equal(panels.board.hidden,false);root.events.focusout({relatedTarget:null});assert.equal(panels.board.hidden,true);
for(let i=0;i<8;i++) {workspace.events.click();board.events.click();root.events.focusout({relatedTarget:{}})}
assert.ok(Object.values(panels).every(panel=>panel.hidden));
const css=read('app/css/fidelity-v2.css');assert.match(css,/fidelity-context-panel\[hidden\] \{ display: none/);assert.match(css,/fidelity-context-trigger:focus-visible/);
console.log('PASS: current-only truthful context, board label provenance, ARIA, toggle/repeat, one open disclosure, Escape/focus restoration, outside click/focus exit; no network or state mutations. Native browser QA remains separate.');
