// Actual detail/card listeners, decision controller, forward dialog and detail closer.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const main=read('app/js/main.js'), ui=read('app/js/ui.js');
const controller=main.slice(main.indexOf('const pendingHomologationDecisions'),main.indexOf('// --- PONTO DE ENTRADA ---'));
const detail=main.slice(main.indexOf("    for (const [id, decision] of [['modal-approve-btn'"),main.indexOf("    document.getElementById('editTaskBtn')"));
const card=main.slice(main.indexOf('        const decisionBtn ='),main.indexOf('        const publishBtn ='));
const closer=ui.slice(ui.indexOf('export function closeApprovedTaskHistory'),ui.indexOf('export function closeTaskHistory')).replace('export function','function');
const forward=read('app/js/homologation-v2.js').replaceAll('export function','function');
const classes=(...values)=>{const set=new Set(values);return {contains:v=>set.has(v),add:v=>set.add(v),remove:v=>set.delete(v)};};
function fixture({kind='detail',visible=true,filtered=false,renderError=false}={}) {
 let dialog=null,callback,resolve,reject,writes=0,renders=0,focused=null;const order=[],toasts=[];
 const element=()=>({handlers:{},disabled:false,addEventListener(t,fn){this.handlers[t]=fn;},setAttribute(){},removeAttribute(){}});
 const button={...element(),dataset:{taskId:'A'},classList:classes('forward-btn')};
 const modal={classList:visible?classes('show'):classes('hidden'),querySelector:()=>({style:{},classList:classes()})};
 const target={dataset:{taskId:'A'},closest:()=>null,getClientRects:()=>filtered?[]:[1],querySelectorAll:()=>[],hasAttribute:()=>false,matches:()=>false,focus(){assert.ok(!dialog?.open,'focus restored after forward dialog closes');focused='A';order.push('focus');}};
 const board={querySelectorAll:()=>[target],hasAttribute:()=>false,matches:()=>false,focus(){assert.ok(!dialog?.open);focused='board';order.push('focus');}};
 const document={querySelectorAll:()=>[button],getElementById(id){return id==='homologation-forward-dialog'?dialog:id==='taskHistoryModal'?modal:id==='modal-forward-btn'?button:id==='main-content'?board:null;},body:{appendChild(d){dialog=d;}},createElement(name){if(name!=='dialog')return element();const select={...element(),options:[{value:''}],value:'',appendChild(o){this.options.push(o);}};const form=element(),error=element(),buttons=[element(),element()];return {...element(),select,form,error,buttons,querySelector(s){return s==='select'?select:s==='form'?form:error;},querySelectorAll:()=>buttons,showModal(){this.open=true;},close(){this.open=false;order.push('dialog-close');this.handlers.close();},remove(){dialog=null;}};}};
 const state={lastInteractedTaskId:'A',returnToNotifications:true,tasks:[{id:'A',status:'homologation',_etag:'v1',homologador:{email:'reviewer@example.test'},responsible:[{email:'old@example.test'}]}],currentUser:{userDetails:'reviewer@example.test',userRoles:['travelcash_user']},users:[{email:'new@example.test',name:'New'}]};
 const context={document,state,activeOriginEl:{style:{opacity:'0'}},activeOriginRect:{},isAnimating:false,console,api:{updateTask(id,payload){writes++;assert.equal(id,'A');assert.deepEqual(JSON.parse(JSON.stringify(payload)),{homologationAction:'forward',expectedStatus:'homologation',expectedEtag:'v1',newResponsibleEmail:'new@example.test'});return new Promise((yes,no)=>{resolve=yes;reject=no;});}},ui:{showToast(m,t){toasts.push(t);},renderTaskHistory(){renders++;},updateActiveView(){order.push('view');if(renderError)throw Error('render failed');}},showApprovalSuccess(){throw Error('forward must not show approval feedback');}};
 vm.createContext(context);vm.runInContext(forward+'\n'+closer+'\n'+controller,context);context.ui.closeApprovedTaskHistory=context.closeApprovedTaskHistory;
 if(kind==='detail'){vm.runInContext(detail,context);callback=button.handlers.click;}else callback=vm.runInContext('(async function(e){'+card+'})',context);
 return {context,modal,order,toasts,get dialog(){return dialog;},get writes(){return writes;},get renders(){return renders;},get focused(){return focused;},open:()=>callback({currentTarget:button,stopPropagation(){},target:{closest:()=>button}}),submit:()=>dialog.form.handlers.submit({preventDefault(){}}),success:()=>resolve({id:'A',status:'todo',responsible:[{email:'new@example.test'}],homologador:null}),wrong:()=>resolve({id:'A',status:'homologation'}),fail:()=>reject(Error('network'))};
}
for(const kind of ['detail','card']) {
 const f=fixture({kind});await f.open();f.dialog.select.value='new@example.test';const pending=f.submit();await f.submit();assert.equal(f.writes,1);assert.ok(f.dialog);assert.ok(!f.modal.classList.contains('hidden'));assert.equal(f.focused,null);f.success();await pending;assert.equal(f.dialog,null);assert.ok(f.modal.classList.contains('hidden'));assert.equal(f.focused,'A');assert.equal(f.renders,0);assert.deepEqual(f.order,['view','dialog-close','focus']);assert.equal(f.writes,1);assert.equal(f.context.state.returnToNotifications,false);
}
for(const outcome of ['fail','wrong']){const f=fixture();await f.open();f.dialog.select.value='new@example.test';const pending=f.submit();f[outcome]();await pending;assert.ok(f.dialog);assert.ok(!f.modal.classList.contains('hidden'));assert.equal(f.focused,null);assert.equal(f.dialog.select.value,'new@example.test');assert.ok(f.dialog.buttons.every(b=>!b.disabled));assert.equal(f.toasts.at(-1),'error');}
const cancel=fixture();await cancel.open();cancel.dialog.buttons[0].handlers.click();assert.equal(cancel.writes,0);assert.ok(!cancel.modal.classList.contains('hidden'));
const escape=fixture();await escape.open();let prevented=false;escape.dialog.handlers.cancel({preventDefault(){prevented=true;}});assert.equal(prevented,false);escape.dialog.close();assert.equal(escape.writes,0);assert.ok(!escape.modal.classList.contains('hidden'));
for(const navigation of ['different','closed','closing']){const f=fixture();await f.open();f.dialog.select.value='new@example.test';const pending=f.submit();if(navigation==='different')f.context.state.lastInteractedTaskId='B';if(navigation==='closed')f.modal.classList.add('hidden');if(navigation==='closing'){f.modal.classList.remove('show');f.context.isAnimating=true;}f.success();await pending;assert.equal(f.dialog,null);assert.equal(f.focused,null);assert.equal(f.renders,0);if(navigation!=='closed')assert.ok(!f.modal.classList.contains('hidden'));}
const filtered=fixture({filtered:true});await filtered.open();filtered.dialog.select.value='new@example.test';const p=filtered.submit();filtered.success();await p;assert.equal(filtered.focused,'board');
const render=fixture({renderError:true});await render.open();render.dialog.select.value='new@example.test';const pr=render.submit();render.success();await pr;assert.ok(render.modal.classList.contains('hidden'));assert.equal(render.writes,1);
const noDetail=fixture({visible:false,kind:'card'});await noDetail.open();noDetail.dialog.select.value='new@example.test';const pn=noDetail.submit();noDetail.modal.classList.remove('hidden');noDetail.modal.classList.add('show');noDetail.success();await pn;assert.ok(!noDetail.modal.classList.contains('hidden'),'card action must not close a detail opened later');assert.equal(noDetail.focused,null);
console.log('PASS TC468: actual card/detail, dialog and controller callbacks; confirmed success closes after dialog and restores focus; one write; error/wrong-state/cancel/Escape preserve detail; newer/closed/closing detail protected; filtered target fallback; persisted render-error safe; card-only late detail protected.');
