import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const main=readFileSync(new URL('../app/js/main.js',import.meta.url),'utf8');
const ui=readFileSync(new URL('../app/js/ui.js',import.meta.url),'utf8');
const start=main.indexOf("        const restoreBtn = e.target.closest('.restore-btn');");
const end=main.indexOf('        /// ==========================================',start);
assert.ok(start>=0&&end>start);
const actions=`async function runAction(e) {${main.slice(start,end)}}`;
const confirmStart=ui.indexOf('export function showDestructiveConfirmModal(');
const confirmEnd=ui.indexOf('export async function updateNotificationBadge()',confirmStart);
const confirms=ui.slice(confirmStart,confirmEnd).replace(/export function/g,'function');
const classes=new Set(['hidden']);
const modal={classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)},querySelector:()=>({textContent:''})};
let button;const parent={replaceChild(next){button=next;next.parentNode=parent;}};
const makeButton=()=>({dataset:{},textContent:'',parentNode:parent,cloneNode:()=>makeButton()});button=makeButton();
const cancel={};const icon={parentElement:{classList:{add(){}},dataset:{}},setAttribute(){}};
let updates=[],deletes=[],toasts=[],rerenders=0,activeRenders=0,cancels=0,ordinaryConfirms=0;
let failUpdate=false,failDelete=false;
const state={currentView:'archived'};
const context={state,document:{getElementById:id=>({deleteConfirmModal:modal,confirmDeleteBtn:button,cancelDeleteBtn:cancel,'modal-icon':icon}[id])},window:{},setTimeout:callback=>callback(),requestAnimationFrame:callback=>callback(),api:{async updateTask(id,payload){updates.push([id,JSON.parse(JSON.stringify(payload))]);if(failUpdate)throw new Error('Fixture update failure');},async deleteTask(id){deletes.push(id);if(failDelete)throw new Error('Fixture deletion failure');}},ui:{showToast:(text,type)=>toasts.push([text,type]),renderArchivedTasks:()=>rerenders++,updateActiveView:()=>activeRenders++}};
vm.runInNewContext(confirms+'\n'+actions,context);
context.ui.showDestructiveConfirmModal=context.showDestructiveConfirmModal;
const event=(selector,id)=>({stopPropagation(){},target:{closest:query=>query===selector?{dataset:{taskId:id},classList:{contains:()=>false}}:null}});
await context.runAction(event('.restore-btn','FIX-451'));
assert.deepEqual(updates,[['FIX-451',{status:'todo'}]]);assert.equal(rerenders,1);assert.equal(deletes.length,0);
assert.equal(updates[0][1].progress,undefined,'restore does not reset or invent progress');
failUpdate=true;await context.runAction(event('.restore-btn','FIX-FAIL'));assert.equal(rerenders,1);assert.equal(toasts.at(-1)[1],'error');failUpdate=false;
await context.runAction(event('.delete-btn','FIX-CANCEL'));
assert.equal(button.dataset.intent,'destructive');assert.equal(button.textContent,'Sim, remover');assert.equal(deletes.length,0,'opening confirmation does not delete');
cancel.onclick();assert.equal(deletes.length,0);assert.ok(classes.has('hidden'));
await context.runAction(event('.delete-btn','FIX-DELETE'));
button.onclick();await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(deletes,['FIX-DELETE']);assert.equal(rerenders,2);
failDelete=true;await context.runAction(event('.delete-btn','FIX-FAIL-DELETE'));button.onclick();await new Promise(resolve=>setImmediate(resolve));
assert.equal(rerenders,2);assert.equal(toasts.at(-1)[1],'error');failDelete=false;
// Consecutive dialogs replace the prior action; ordinary dialogs retain blue intent.
context.showDestructiveConfirmModal('Old','Old',()=>deletes.push('STALE'));
context.showConfirmModal('Ordinary','Ordinary',()=>ordinaryConfirms++,()=>cancels++);
assert.equal(button.dataset.intent,'confirm');assert.equal(button.textContent,'Confirmar');
cancel.onclick();assert.equal(cancels,1);assert.equal(ordinaryConfirms,0);assert.ok(!deletes.includes('STALE'));
context.showConfirmModal('Ordinary','Ordinary',()=>ordinaryConfirms++);button.onclick();assert.equal(ordinaryConfirms,1);
state.currentView='list';await context.runAction(event('.delete-btn','FIX-LIST'));button.onclick();await new Promise(resolve=>setImmediate(resolve));assert.equal(activeRenders,1);assert.equal(rerenders,2,'other view callback preserved');
assert.equal(updates.length,2);
console.log(JSON.stringify({status:'passed',scope:'Actual unmodified main.js restore/delete branches and shared confirmation functions, with DOM/API stubs only',checks:['Restore sends exact todo payload with no progress rewrite','Restore failure reports existing error and does not rerender','Delete opens destructive confirmation without writing','Cancellation does not delete','Confirmed delete preserves exact task ID and archive rerender','Deletion failure reports error','Consecutive dialog replacement prevents stale callbacks','Ordinary confirmation retains confirm intent','Navigation to another view keeps its existing rerender callback']},null,2));
