import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../api/createTask/index.js',import.meta.url),'utf8');
let creates=[],counter=0;const tasks={item(){return {async patch(){counter++;return {resource:{currentId:473}};}}},items:{async create(value){creates.push(value);return {resource:{...value,_etag:"created-v1"}};}}};
const module={exports:{}};vm.runInNewContext(source,{module,Buffer,console,process:{env:{}},require(name){if(name==='@azure/cosmos')return {CosmosClient:class{database(){return {container:()=>tasks};}}};if(name==='axios')return {};throw Error(name);}});
async function call(status){const log=()=>{};log.error=()=>{};const context={log,bindings:{}};await module.exports(context,{headers:{'x-ms-client-principal':Buffer.from(JSON.stringify({userDetails:'user@example.test'})).toString('base64')},body:{title:'Test',description:'Test',responsible:[{email:'user@example.test'}],status,homologador:{email:'reviewer@example.test'}}});if(context.bindings.signalRMessage)assert.equal(context.bindings.signalRMessage.arguments[0]._etag,'created-v1');return context.res;}
for(const status of ['homologation','publication','done','inprogress'])assert.equal((await call(status)).status,400);
assert.equal(counter,0);assert.equal(creates.length,0);const created=await call('todo');assert.equal(created.status,undefined);assert.equal(created.body._etag,'created-v1');const ui=await import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('../app/js/homologation-v2.js',import.meta.url),'utf8')).toString('base64'));const assignment=ui.homologationAssignmentPayload(created.body,'reviewer@example.test',[{email:'reviewer@example.test'}]);assert.equal(assignment.expectedEtag,'created-v1');assert.equal(assignment.expectedStatus,'todo');assert.equal(assignment.status,'homologation');assert.equal(creates.length,1);assert.equal(creates[0].status,'todo');assert.equal(creates[0].homologador,undefined);
console.log('PASS TC473 creation: Fila-only creation; rejected direct homologation; persisted ETag in HTTP/SignalR; create-to-assignment payload. Deletion coordination covered separately.');
