import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source = readFileSync(new URL('../app/js/archive-v2.js', import.meta.url), 'utf8');
const helpers = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const {renderArchiveRows, renderArchiveShell, archiveResponsibleNames, archiveUpdatedLabel, applyArchiveProjectColors} = helpers;
const fixture = {id:'FIX-451',status:'done',title:'Um título longo, com acentos & <conteúdo> "seguro"',project:'Projeto <Exemplo>',projectColor:'#C026D3',responsible:[{name:'Ana Sobrenome Completo',email:'ana@example.invalid'},'Bruno Sobrenome Completo',{displayName:'Carla Nome Integral'}],updatedAt:'2026-10-06T23:59:00Z',progress:100};
const users=[{name:'ana',email:'ana@example.invalid',displayName:'Ana Sobrenome Completo'}];
const freeze = value => {if(value && typeof value === 'object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
freeze(fixture);freeze(users);
const snapshot=JSON.stringify({fixture,users});
const html=renderArchiveRows([fixture],users);
assert.ok(html.includes('data-status="done"'));
assert.ok(html.includes('Arquivado · Concluída'));
assert.ok(html.includes('Ana Sobrenome Completo, Bruno Sobrenome Completo, Carla Nome Integral'));
assert.ok(html.includes('06/10/2026'));
assert.ok(html.includes('Última atualização'));
assert.ok(html.includes('data-project-color="#C026D3"'));
assert.ok(html.includes('&lt;conteúdo&gt; &quot;seguro&quot;'));
assert.ok(!html.includes('<conteúdo>'));
assert.equal(JSON.stringify({fixture,users}),snapshot,'render does not mutate tasks, people, progress or dates');
assert.equal(archiveResponsibleNames(null),'Sem responsável');
assert.equal(archiveResponsibleNames([]),'Sem responsável');
assert.equal(archiveResponsibleNames([null,{},'']),'Sem responsável');
assert.equal(archiveResponsibleNames([{email:'unknown@example.invalid'}]),'unknown@example.invalid');
assert.equal(archiveResponsibleNames(['ana'],[...users,{name:'ana',displayName:'Outra Ana'}]),'ana','ambiguous directory name is not guessed');
for(const value of [null,undefined,'',' ','invalid','not-a-date',0,{},[]])assert.equal(archiveUpdatedLabel(value),'Não informada');
for(const value of ['#abc','#ABCDEF','#000000','rgb(12, 34, 56)','hsl(220, 80%, 50%)','rebeccapurple','#12345678']) {
 const colorHTML=renderArchiveRows([{...fixture,projectColor:value}]);
 assert.ok(colorHTML.includes(`data-project-color="${value}"`));
 const dot={dataset:{projectColor:value},style:{}};
 applyArchiveProjectColors({querySelectorAll:()=>[dot]});
 assert.equal(dot.style.backgroundColor,value,'exact supplied color passed only to CSS backgroundColor');
 assert.deepEqual(Object.keys(dot.style),['backgroundColor']);
}
assert.equal(archiveResponsibleNames([{name:'ana'}],users),'ana','no users-directory identity resolution');
const missing=renderArchiveRows([{id:'FIX-MISSING',status:'done'}]);
for(const text of ['Título não informado','Sem projeto','Sem responsável','Não informada'])assert.ok(missing.includes(text));
assert.ok(!missing.includes('Invalid Date'));
const empty=renderArchiveRows([]);
assert.ok(empty.includes('Nenhuma tarefa arquivada') && empty.includes('role="status"'));
assert.ok(!empty.includes('restore-btn') && !empty.includes('delete-btn'));
assert.throws(()=>renderArchiveRows({items:[]}),/Resposta do arquivo inválida/);
const many=Array.from({length:300},(_,i)=>({...fixture,id:`FIX-${i}`}));
const manyHTML=renderArchiveRows(many,users);
assert.equal((manyHTML.match(/class="restore-btn /g)||[]).length,300);
assert.equal((manyHTML.match(/class="delete-btn /g)||[]).length,300);
assert.ok(manyHTML.includes('300 tarefas nesta consulta'));
assert.ok(manyHTML.indexOf('data-task-id="FIX-0"')<manyHTML.indexOf('data-task-id="FIX-299"'),'endpoint order preserved');
const mixed=renderArchiveRows([fixture,{...fixture,id:'FIX-ACTIVE',status:'publication',progress:100},{...fixture,id:'FIX-UNKNOWN',status:'future-status'}]);
assert.equal((mixed.match(/class="task-list-row/g)||[]).length,3,'returned row set preserved');
assert.equal((mixed.match(/Arquivado · Concluída/g)||[]).length,1,'only done is called archived');
assert.ok(mixed.includes('Publicação · Estado divergente'));
assert.ok(mixed.includes('future-status · Estado divergente'));
assert.ok(mixed.includes('role="alert"'));
const attack='\"><img src=x onerror=alert(1)> & \' <script>bad()</script>';
const escaped=renderArchiveRows([{...fixture,id:attack,title:attack,project:attack,responsible:[attack],projectColor:attack,status:attack}]);
assert.ok(!escaped.includes('<img') && !escaped.includes('<script>') && !escaped.includes('background-color:'));
assert.ok(escaped.includes('&lt;img'));
assert.ok(!/\b(?:line-through|truncate|grayscale|opacity-75)\b/.test(html));
assert.equal((html.match(/type="button"/g)||[]).length,2);
for(const cls of ['restore-btn','delete-btn'])assert.ok(new RegExp(`class="${cls}[^>]+data-task-id="FIX-451"`).test(html));

// Execute the actual async renderer with an isolated DOM target and API stub.
const uiSource=readFileSync(new URL('../app/js/ui.js',import.meta.url),'utf8');
const start=uiSource.indexOf('export async function renderArchivedTasks() {');
const end=uiSource.indexOf('// --- RENDERIZAÇÃO: UTILIZADORES ---',start);
const rendererSource=uiSource.slice(start,end).replace('export async function','async function');
const container={innerHTML:'',querySelectorAll:()=>[]};let resolveFetch,rejectFetch,calls=0,icons=0;
const context={document:{getElementById:id=>{assert.equal(id,'archivedView');return container;}},lucide:{createIcons(){icons++;}},state:{users},renderArchiveRows,renderArchiveShell,applyArchiveProjectColors,fetchArchivedTasks(){calls++;return new Promise((resolve,reject)=>{resolveFetch=resolve;rejectFetch=reject;});},console:{error(){}}};
vm.runInNewContext(rendererSource,context);
let pending=context.renderArchivedTasks();
assert.ok(container.innerHTML.includes('Carregando arquivados') && container.innerHTML.includes('aria-busy="true"'));
assert.ok(!container.innerHTML.includes('Nenhuma tarefa arquivada'),'loading is not empty');
resolveFetch([fixture]);await pending;
assert.ok(container.innerHTML.includes('FIX-451'));
assert.ok(!container.innerHTML.includes('aria-busy="true"'));
pending=context.renderArchivedTasks();resolveFetch([]);await pending;
assert.ok(container.innerHTML.includes('Nenhuma tarefa arquivada'));
pending=context.renderArchivedTasks();rejectFetch(new Error('Network unavailable'));await pending;
assert.ok(container.innerHTML.includes('role="alert"') && container.innerHTML.includes('Não foi possível carregar o arquivo'));
assert.ok(!container.innerHTML.includes('Nenhuma tarefa arquivada'),'failure is not empty');
pending=context.renderArchivedTasks();resolveFetch([fixture]);await pending;
assert.ok(container.innerHTML.includes('FIX-451'),'later reopening recovers');
assert.equal(calls,4);assert.equal(icons,7);
console.log(JSON.stringify({status:'passed',scope:'Pure presentation fixtures and the real async renderer with network/DOM stubs',checks:['Full text and all supplied responsible names without directory lookup','Honest missing/invalid updatedAt labels with UTC date','Safe project-color preservation and text/attribute escaping','No task/progress/date/user mutation','Empty, malformed response, loading, failure, reopen recovery','300 returned rows in existing endpoint order','publication100 and unknown status retained without invented completion','Native labelled restore/delete buttons keep exact task IDs']},null,2));
